name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: EditorConfig lint
      uses: greut/eclint-action@v0.1.1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Build with dotnet
      run: dotnet build
    - name: validate-license-action
      uses: datreeio/validate-license-action@v1.0.0
